version: '3.8'
services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=your_database
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=your_database
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
